### PR TITLE
Refactor `lib.py`

### PR DESCRIPTION
**Pull request by s3n-w6i**
It now lives outside the main module in `debugging/cli.py` and accepts arbitrary file paths.

Merge #15 first.

### CODE REVIEW

**Review by TheFirstGameruler — DISMISSED** [review]
top

**Review by orlandoisepic — DISMISSED** [review]
See my comment on #15. Well done

**Review by TheFirstGameruler — APPROVED** [review]
NP

**Review by TheFirstGameruler — APPROVED** [review]
NPx2

**Pull request merged**
